# Operazioni con i tensori

In [14]:
import tensorflow as tf
import numpy as np

In [8]:
a = tf.convert_to_tensor([[1, 2], [3, 4]])
b = tf.convert_to_tensor([[5, 6], [7, 8]])

In [9]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [10]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [11]:
tf.reduce_max(a, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [12]:
tf.reduce_max(a, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [4]])>

In [13]:
a.numpy()

array([[1, 2],
       [3, 4]])

## è possibile utilizzare le operazioni di Tensorflow su tensori numpy

In [15]:
tf.reduce_max(np.array([[1, 2], [3, 4]]))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## e viceversa

In [18]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
np.sum(a)

10

## broadcasting

In [23]:
tf.convert_to_tensor([[1, 2], [3, 4]]) + tf.convert_to_tensor([10, 11])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [13, 15]])>

In [24]:
## non è permesso combinare tensori di tipi differenti

In [25]:
a = tf.convert_to_tensor([1, 2, 3])
b = tf.convert_to_tensor([4, 5, 6.])

In [26]:
a + b

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: add/

In [47]:
tf.cast(a, dtype=tf.float32) + b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

## Variabili

In [48]:
v = tf.Variable(initial_value=[1, 2, 3])

### le variabili sono modificabili

In [51]:
v.assign([4, 5, 6])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>

In [54]:
v[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([10,  5,  6])>